### ISSUE TITLE
TypeError: 'type' object is not subscriptable after April 19th's Update

### ISSUE THREAD

**Issue by kilikilikid** [gregorias/anki-code-highlighter#3]
The error shows like this:
![image](https://user-images.githubusercontent.com/21957844/164090921-ab20f37f-dc6b-4252-af5d-ed0f0cacbeb4.png)

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Highlight Code⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\xxxx\AppData\Roaming\Anki2\addons21\112228974\__init__.py", line 3, in <module>
    from . import main
  File "C:\Users\xxxx\AppData\Roaming\Anki2\addons21\112228974\main.py", line 17, in <module>
    from .assets import AnkiAssetManager, sync_assets
  File "C:\Users\xxxx\AppData\Roaming\Anki2\addons21\112228974\assets.py", line 70, in <module>
    def list_my_assets(dir: pathlib.Path) -> list[str]:
TypeError: 'type' object is not subscriptable

**Comment by gregorias** [comment]
Thank you reporting and I apologize for the inconvienence. My testing regime did not include previous Anki versions.
