### ISSUE TITLE
Failed to load Addon uppon Starting Anki

### ISSUE THREAD

**Issue by M4l1K** [gregorias/anki-code-highlighter#61]
### This is the error message:
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Syntax Highlighting for Code⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\maxkr\AppData\Roaming\Anki2\addons21\1463041493\__init__.py", line 15, in <module>
    from . import main
  File "C:\Users\maxkr\AppData\Roaming\Anki2\addons21\1463041493\main.py", line 54, in <module>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers()}
  File "C:\Users\maxkr\AppData\Roaming\Anki2\addons21\1463041493\main.py", line 54, in <dictcomp>
    LANGUAGES_MAP = {lex[0]: lex[1][0] for lex in get_all_lexers()}
IndexError: tuple index out of range
⁩
### My Anki
Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5

### My System
Windows 11

If you need more info just ask :)

Would really appreciate some help

**Comment by gregorias** [comment]
This is an error message for another plugin that is not mine, [Syntax Highlighting for Code](https://ankiweb.net/shared/info/1463041493). My plugin is [here](https://ankiweb.net/shared/info/112228974).
